version: '3.8'

services:
  tracker:
    build:
      context: ./main_task
      dockerfile: Dockerfile
    volumes:
      - ./bitcoin.db:/app/bitcoin.db
    command: python main.py
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: flask/Dockerfile.db
    ports:
      - "5000:5000"
    volumes:
      - ./bitcoin.db:/app/bitcoin.db
